const teamMemberData = [
  {
    fbLink: "",
    twLink: "",
    skLink: "",
    liLink: "",
    imgSrc: "https://i.ibb.co/JC4skS0/team-animate.jpg",
    name: "PANKAJ SWAMI VAISHNAV",
    position: "SOFTWARE ENGINEER",
  },
  {
    fbLink: "",
    twLink: "",
    skLink: "",
    liLink: "",
    imgSrc: "https://i.ibb.co/JC4skS0/team-animate.jpg",
    name: "PANKAJ SWAMI VAISHNAV",
    position: "SOFTWARE ENGINEER",
  },
  {
    fbLink: "",
    twLink: "",
    skLink: "",
    liLink: "",
    imgSrc: "https://i.ibb.co/JC4skS0/team-animate.jpg",
    name: "PANKAJ SWAMI VAISHNAV",
    position: "SOFTWARE ENGINEER",
  },
  {
    fbLink: "",
    twLink: "",
    skLink: "",
    liLink: "",
    imgSrc: "https://i.ibb.co/JC4skS0/team-animate.jpg",
    name: "PANKAJ SWAMI VAISHNAV",
    position: "SOFTWARE ENGINEER",
  },
  {
    fbLink: "",
    twLink: "",
    skLink: "",
    liLink: "",
    imgSrc: "https://i.ibb.co/JC4skS0/team-animate.jpg",
    name: "PANKAJ SWAMI VAISHNAV",
    position: "SOFTWARE ENGINEER",
  },
  {
    fbLink: "",
    twLink: "",
    skLink: "",
    liLink: "",
    imgSrc: "https://i.ibb.co/JC4skS0/team-animate.jpg",
    name: "PANKAJ SWAMI VAISHNAV",
    position: "SOFTWARE ENGINEER",
  },
  {
    fbLink: "",
    twLink: "",
    skLink: "",
    liLink: "",
    imgSrc: "https://i.ibb.co/JC4skS0/team-animate.jpg",
    name: "PANKAJ SWAMI VAISHNAV",
    position: "SOFTWARE ENGINEER",
  },
  {
    fbLink: "",
    twLink: "",
    skLink: "",
    liLink: "",
    imgSrc: "https://i.ibb.co/JC4skS0/team-animate.jpg",
    name: "PANKAJ SWAMI VAISHNAV",
    position: "SOFTWARE ENGINEER",
  },
  {
    fbLink: "",
    twLink: "",
    skLink: "",
    liLink: "",
    imgSrc: "https://i.ibb.co/JC4skS0/team-animate.jpg",
    name: "PANKAJ SWAMI VAISHNAV",
    position: "SOFTWARE ENGINEER",
  },
  {
    fbLink: "",
    twLink: "",
    skLink: "",
    liLink: "",
    imgSrc: "https://i.ibb.co/JC4skS0/team-animate.jpg",
    name: "PANKAJ SWAMI VAISHNAV",
    position: "SOFTWARE ENGINEER",
  },
  {
    fbLink: "",
    twLink: "",
    skLink: "",
    liLink: "",
    imgSrc: "https://i.ibb.co/JC4skS0/team-animate.jpg",
    name: "PANKAJ SWAMI VAISHNAV",
    position: "SOFTWARE ENGINEER",
  },
  {
    fbLink: "",
    twLink: "",
    skLink: "",
    liLink: "",
    imgSrc: "https://i.ibb.co/JC4skS0/team-animate.jpg",
    name: "PANKAJ SWAMI VAISHNAV",
    position: "SOFTWARE ENGINEER",
  },
];

export default teamMemberData;
